// packages/vue/src/components/CardList.vue
<template>
  <div
    role="list"
    :class="gridClasses"
  >
    <div
      v-for="(item, index) in items"
      :key="index"
      role="listitem"
    >
      <slot name="item" :item="item" :index="index">
        {{ item }}
      </slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

export type CardListCols = 1 | 2 | 3 | 4 | 5 | 6;
export type CardListGap = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 8 | 10 | 12;

export interface CardListProps {
  items: any[];
  cols?: CardListCols;
  gap?: CardListGap;
  class?: string;
}

const props = withDefaults(defineProps<CardListProps>(), {
  cols: 3,
  gap: 4,
  class: '',
});

const getColsClass = (): string => {
  const colsMap: Record<CardListCols, string> = {
    1: 'lg:grid-cols-1',
    2: 'lg:grid-cols-2',
    3: 'lg:grid-cols-3',
    4: 'lg:grid-cols-4',
    5: 'lg:grid-cols-5',
    6: 'lg:grid-cols-6',
  };
  return colsMap[props.cols];
};

const getGapClass = (): string => {
  const gapMap: Record<CardListGap, string> = {
    0: 'gap-0',
    1: 'gap-1',
    2: 'gap-2',
    3: 'gap-3',
    4: 'gap-4',
    5: 'gap-5',
    6: 'gap-6',
    8: 'gap-8',
    10: 'gap-10',
    12: 'gap-12',
  };
  return gapMap[props.gap];
};

const gridClasses = computed(() => {
  return [
    'grid',
    'grid-cols-1',
    'md:grid-cols-2',
    getColsClass(),
    getGapClass(),
    props.class,
  ].filter(Boolean).join(' ');
});
</script>

// packages/react/src/components/organisms/CardList/CardList.tsx
import React from 'react';
import { CardListProps } from './types';
import { cn } from '../../../lib/utils';

export const CardList: React.FC<CardListProps> = ({
  items,
  cols = 3,
  gap = 4,
  className
}) => {
  // Dynamic grid columns class based on cols prop
  const getColsClass = () => {
    switch (cols) {
      case 1:
        return 'lg:grid-cols-1';
      case 2:
        return 'lg:grid-cols-2';
      case 3:
        return 'lg:grid-cols-3';
      case 4:
        return 'lg:grid-cols-4';
      case 5:
        return 'lg:grid-cols-5';
      case 6:
        return 'lg:grid-cols-6';
      default:
        return 'lg:grid-cols-3';
    }
  };

  // Dynamic gap class based on gap prop
  const getGapClass = () => {
    switch (gap) {
      case 0:
        return 'gap-0';
      case 1:
        return 'gap-1';
      case 2:
        return 'gap-2';
      case 3:
        return 'gap-3';
      case 4:
        return 'gap-4';
      case 5:
        return 'gap-5';
      case 6:
        return 'gap-6';
      case 8:
        return 'gap-8';
      case 10:
        return 'gap-10';
      case 12:
        return 'gap-12';
      default:
        return 'gap-4';
    }
  };

  return (
    <div
      role="list"
      className={cn(
        'grid',
        'grid-cols-1',
        'md:grid-cols-2',
        getColsClass(),
        getGapClass(),
        className
      )}
    >
      {items.map((item, index) => (
        <div key={index} role="listitem">
          {item}
        </div>
      ))}
    </div>
  );
};
