// packages/vue/src/components/Select.vue
<template>
  <div 
    ref="selectRef"
    :class="['relative', fullWidth ? 'w-full' : 'inline-block w-full', isOpen && 'z-50']"
  >
    <!-- Trigger -->
    <div
      role="combobox"
      :aria-expanded="isOpen"
      aria-haspopup="listbox"
      :aria-invalid="invalid"
      :aria-disabled="disabled"
      :tabindex="disabled ? -1 : 0"
      :class="triggerClasses"
      @click="handleToggle"
      @keydown="handleKeyDown"
    >
      <span :class="[selectedOption ? 'text-gray-900 dark:text-white' : 'text-gray-500 dark:text-gray-400']">
        {{ selectedOption ? selectedOption.label : placeholder }}
      </span>
      
      <div class="flex items-center gap-1">
        <svg
          v-if="loading"
          class="w-4 h-4 text-gray-500 dark:text-gray-400 animate-spin"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
        >
          <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
          <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
        </svg>
        
        <button
          v-if="clearable && modelValue"
          type="button"
          @click.stop="handleClear"
          class="flex items-center justify-center w-4 h-4 text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 transition-colors"
          aria-label="Clear selection"
          tabindex="-1"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <line x1="18" y1="6" x2="6" y2="18"></line>
            <line x1="6" y1="6" x2="18" y2="18"></line>
          </svg>
        </button>
        
        <svg
          :class="['w-4 h-4 text-gray-500 dark:text-gray-400 transition-transform', isOpen && 'rotate-180']"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <polyline points="6 9 12 15 18 9"></polyline>
        </svg>
      </div>
    </div>
    
    <!-- Dropdown Menu -->
    <div
      v-if="isOpen"
      role="listbox"
      :class="menuClasses"
      :style="{ maxHeight: `${maxMenuHeight}px` }"
    >
      <!-- Search Input -->
      <div v-if="searchable" class="p-2 border-b border-border">
        <div class="relative">
          <svg
            class="absolute left-2 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500 dark:text-gray-400"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <circle cx="11" cy="11" r="8"></circle>
            <path d="m21 21-4.35-4.35"></path>
          </svg>
          <input
            ref="searchInputRef"
            v-model="searchTerm"
            type="text"
            placeholder="Search..."
            class="w-full pl-8 pr-2 py-1.5 text-sm border border-border rounded bg-background text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
            @click.stop
            @keydown="handleKeyDown"
          />
        </div>
      </div>
      
      <!-- Options List -->
      <div class="overflow-y-auto" :style="{ maxHeight: searchable ? `${maxMenuHeight - 60}px` : `${maxMenuHeight}px` }">
        <div
          v-for="(option, index) in filteredOptions"
          :key="option.value"
          role="option"
          :aria-selected="option.value === modelValue"
          :aria-disabled="option.disabled"
          :class="optionClasses(option, index)"
          @click="!option.disabled && handleOptionClick(option.value)"
          @mouseenter="highlightedIndex = index"
        >
          <span>{{ option.label }}</span>
          <svg
            v-if="option.value === modelValue"
            class="w-4 h-4"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <polyline points="20 6 9 17 4 12"></polyline>
          </svg>
        </div>
        <div v-if="filteredOptions.length === 0" class="px-3 py-2 text-sm text-gray-500 dark:text-gray-400 text-center">
          No options found
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, nextTick } from 'vue';

export interface SelectOption {
  label: string;
  value: string;
  disabled?: boolean;
}

export interface SelectProps {
  modelValue?: string;
  options?: SelectOption[];
  placeholder?: string;
  disabled?: boolean;
  invalid?: boolean;
  fullWidth?: boolean;
  searchable?: boolean;
  clearable?: boolean;
  loading?: boolean;
  maxMenuHeight?: number;
  class?: string;
}

const props = withDefaults(defineProps<SelectProps>(), {
  modelValue: '',
  options: () => [],
  placeholder: 'Select an option...',
  disabled: false,
  invalid: false,
  fullWidth: false,
  searchable: false,
  clearable: false,
  loading: false,
  maxMenuHeight: 200,
  class: '',
});

const emit = defineEmits<{
  'update:modelValue': [value: string];
  'change': [value: string];
}>();

const selectRef = ref<HTMLDivElement | null>(null);
const searchInputRef = ref<HTMLInputElement | null>(null);
const isOpen = ref(false);
const searchTerm = ref('');
const highlightedIndex = ref(-1);

const selectedOption = computed(() => 
  props.options.find(option => option.value === props.modelValue)
);

const filteredOptions = computed(() => {
  if (!props.searchable || !searchTerm.value) {
    return props.options;
  }
  
  const term = searchTerm.value.toLowerCase();
  return props.options.filter(option => 
    option.label.toLowerCase().includes(term)
  );
});

const handleToggle = () => {
  if (props.disabled || props.loading) return;
  
  isOpen.value = !isOpen.value;
  
  if (isOpen.value && props.searchable) {
    nextTick(() => {
      searchInputRef.value?.focus();
    });
  }
};

const handleClear = () => {
  emit('update:modelValue', '');
  emit('change', '');
};

const handleOptionClick = (value: string) => {
  emit('update:modelValue', value);
  emit('change', value);
  isOpen.value = false;
  searchTerm.value = '';
  highlightedIndex.value = -1;
};

const handleKeyDown = (event: KeyboardEvent) => {
  if (props.disabled || props.loading) return;
  
  switch (event.key) {
    case 'Enter':
      event.preventDefault();
      if (!isOpen.value) {
        isOpen.value = true;
      } else if (highlightedIndex.value >= 0 && highlightedIndex.value < filteredOptions.value.length) {
        const option = filteredOptions.value[highlightedIndex.value];
        if (!option.disabled) {
          handleOptionClick(option.value);
        }
      }
      break;
    case 'Escape':
      event.preventDefault();
      if (isOpen.value) {
        isOpen.value = false;
        searchTerm.value = '';
        highlightedIndex.value = -1;
      }
      break;
    case 'ArrowDown':
      event.preventDefault();
      if (!isOpen.value) {
        isOpen.value = true;
      } else {
        highlightedIndex.value = Math.min(highlightedIndex.value + 1, filteredOptions.value.length - 1);
      }
      break;
    case 'ArrowUp':
      event.preventDefault();
      highlightedIndex.value = Math.max(highlightedIndex.value - 1, 0);
      break;
  }
};

// Click outside to close
const handleClickOutside = (event: MouseEvent) => {
  if (selectRef.value && !selectRef.value.contains(event.target as Node)) {
    isOpen.value = false;
    searchTerm.value = '';
    highlightedIndex.value = -1;
  }
};

watch(isOpen, (newValue) => {
  if (newValue) {
    document.addEventListener('click', handleClickOutside);
  } else {
    document.removeEventListener('click', handleClickOutside);
  }
});

const triggerClasses = computed(() => {
  return [
    'flex h-11 w-full items-center justify-between rounded-lg border border-gray-300 bg-gray-50 px-4 py-2.5 text-sm text-gray-900',
    'cursor-pointer transition-colors',
    'focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary',
    'disabled:cursor-not-allowed disabled:bg-gray-200 disabled:text-gray-500 disabled:border-gray-200',
    'dark:bg-gray-700 dark:border-gray-600 dark:text-white',
    'dark:focus:ring-primary dark:focus:border-primary',
    'dark:disabled:bg-gray-600 dark:disabled:text-gray-400 dark:disabled:border-gray-600',
    props.invalid && 'border-red-500 focus:ring-red-500 focus:border-red-500 dark:border-red-500',
    props.class,
  ].filter(Boolean).join(' ');
});

const menuClasses = computed(() => {
  return [
    'absolute z-50 w-full mt-2 rounded-lg border border-border bg-card shadow-lg overflow-hidden',
  ].join(' ');
});

const optionClasses = (option: SelectOption, index: number) => {
  return [
    'flex items-center justify-between px-3 py-2 text-sm cursor-pointer transition-colors',
    option.value === props.modelValue && 'bg-primary/10 text-primary font-medium',
    option.disabled && 'opacity-50 cursor-not-allowed',
    !option.disabled && option.value !== props.modelValue && 'hover:bg-muted',
    highlightedIndex.value === index && !option.disabled && 'bg-muted',
  ].filter(Boolean).join(' ');
};
</script>

// packages/react/src/components/atoms/Select/Select.tsx
import React, { useState, useRef } from 'react';
import { SelectProps, SelectOption } from './types';
import { cn } from '../../../lib/utils';
import { ChevronDown, X, Search, Loader2, Check } from 'lucide-react';
import { useSelectNavigation } from '../../../hooks/useSelectNavigation';
import { useClickOutside } from '../../../hooks/useClickOutside';

export const Select = React.forwardRef<HTMLDivElement, SelectProps>(
  ({ 
    className, 
    disabled = false,
    invalid = false,
    fullWidth = false,
    options = [],
    placeholder = "Select an option...",
    value,
    onChange,
    // New Phase 2 props
    searchable = false,
    clearable = false,
    loading = false,
    maxMenuHeight = 200,
    filterFunction,
    renderOption,
    onFocus,
    onBlur,
    ...props 
  }, ref) => {
    const [isOpen, setIsOpen] = useState(false);
    const [isFocused, setIsFocused] = useState(false);
    
    const selectRef = useRef<HTMLDivElement>(null);
    const searchInputRef = useRef<HTMLInputElement>(null);

    const selectedOption = options.find(option => option.value === value);

    const {
      filteredOptions,
      highlightedIndex,
      searchTerm,
      setSearchTerm,
      handleKeyDown,
      handleOptionClick,
      listRef,
      setOptionRef,
      clearSearch
    } = useSelectNavigation({
      options,
      isOpen,
      onSelect: (selectedValue) => {
        onChange?.(selectedValue);
      },
      onClose: () => setIsOpen(false),
      searchable,
      filterFunction
    });

    useClickOutside(selectRef, () => {
      if (isOpen) {
        setIsOpen(false);
        setIsFocused(false);
        onBlur?.();
      }
    });

    const handleToggle = () => {
      if (disabled || loading) return;
      
      if (!isOpen) {
        setIsOpen(true);
        setIsFocused(true);
        onFocus?.();
        // Focus search input if searchable
        setTimeout(() => {
          if (searchable && searchInputRef.current) {
            searchInputRef.current.focus();
          }
        }, 0);
      } else {
        setIsOpen(false);
        setIsFocused(false);
        onBlur?.();
      }
    };

    const handleClear = (e: React.MouseEvent) => {
      e.stopPropagation();
      onChange?.('');
    };

    const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
      setSearchTerm(e.target.value);
    };

    return (
      <div 
        ref={selectRef}
        className={cn(
          'relative', 
          fullWidth ? 'w-full' : 'inline-block w-full',
          isOpen && 'z-50'
        )}
        {...props}
      >
        {/* Trigger */}
        <div
          ref={ref}
          role="combobox"
          aria-expanded={isOpen}
          aria-haspopup="listbox"
          aria-invalid={invalid}
          aria-disabled={disabled}
          tabIndex={disabled ? -1 : 0}
          className={cn(
            'flex h-11 w-full items-center justify-between rounded-lg border border-gray-300 bg-gray-50 px-4 py-2.5 text-sm text-gray-900',
            'cursor-pointer transition-colors',
            'focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary',
            'disabled:cursor-not-allowed disabled:bg-gray-200 disabled:text-gray-500 disabled:border-gray-200',
            'dark:bg-gray-700 dark:border-gray-600 dark:text-white',
            'dark:focus:ring-primary dark:focus:border-primary',
            'dark:disabled:bg-gray-600 dark:disabled:text-gray-400 dark:disabled:border-gray-600',
            invalid && 'border-red-500 focus:ring-red-500 focus:border-red-500 dark:border-red-500',
            disabled && 'cursor-not-allowed',
            className
          )}
          onClick={handleToggle}
          onKeyDown={handleKeyDown}
        >
          <div className="flex-1 truncate">
            {selectedOption ? (
              <span className="text-gray-900 dark:text-white">
                {selectedOption.label}
              </span>
            ) : (
              <span className="text-gray-500 dark:text-gray-400">
                {placeholder}
              </span>
            )}
          </div>
          
          <div className="flex items-center gap-1 ml-2">
            {loading && (
              <Loader2 className="w-4 h-4 text-gray-500 dark:text-gray-400 animate-spin" />
            )}
            
            {clearable && selectedOption && !loading && (
              <button
                type="button"
                onClick={handleClear}
                className="flex items-center justify-center w-4 h-4 text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 transition-colors"
                aria-label="Clear selection"
                tabIndex={-1}
              >
                <X className="w-3 h-3" />
              </button>
            )}
            
            <ChevronDown 
              className={cn(
                "w-4 h-4 text-gray-500 dark:text-gray-400 transition-transform",
                isOpen && "rotate-180"
              )} 
            />
          </div>
        </div>

        {/* Dropdown Menu */}
        {isOpen && (
          <div 
            className={cn(
              "absolute z-50 w-full mt-1 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg shadow-lg overflow-hidden flex flex-col",
              "animate-in fade-in-0 zoom-in-95 data-[side=bottom]:slide-in-from-top-2"
            )}
            style={{ maxHeight: maxMenuHeight }}
          >
            {searchable && (
              <div className="p-2 border-b border-gray-200 dark:border-gray-700 flex-shrink-0">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500 dark:text-gray-400" />
                  <input
                    ref={searchInputRef}
                    type="text"
                    placeholder="Search options..."
                    value={searchTerm}
                    onChange={handleSearchChange}
                    className={cn(
                      "w-full pl-9 pr-3 py-2 text-sm rounded-md border border-gray-300 dark:border-gray-600",
                      "bg-white dark:bg-gray-700 text-gray-900 dark:text-white",
                      "focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary",
                      "placeholder:text-gray-500 dark:placeholder:text-gray-400"
                    )}
                  />
                </div>
              </div>
            )}
            
            <div
              ref={listRef}
              role="listbox"
              className="flex-1 overflow-y-auto p-1 min-h-0"
            >
              {filteredOptions.length === 0 ? (
                <div className="px-3 py-2 text-sm text-gray-500 dark:text-gray-400 text-center">
                  No options found
                </div>
              ) : (
                filteredOptions.map((option, index) => {
                  const isHighlighted = index === highlightedIndex;
                  const isSelected = option.value === value;
                  
                  return (
                    <div
                      key={option.value}
                      ref={setOptionRef(index)}
                      role="option"
                      aria-selected={isSelected}
                      aria-disabled={option.disabled}
                      className={cn(
                        "relative flex items-center px-3 py-2 text-sm rounded-md cursor-pointer",
                        "transition-colors",
                        isHighlighted && "bg-gray-100 dark:bg-gray-700",
                        isSelected && "bg-primary/10 text-primary dark:bg-primary/20",
                        option.disabled && "opacity-50 cursor-not-allowed",
                        !option.disabled && !isHighlighted && !isSelected && "hover:bg-gray-50 dark:hover:bg-gray-750"
                      )}
                      onClick={() => !option.disabled && handleOptionClick(option.value)}
                    >
                      <div className="flex-1 truncate">
                        {renderOption ? renderOption(option, isHighlighted) : option.label}
                      </div>
                      
                      {isSelected && (
                        <Check className="w-4 h-4 text-primary ml-2 flex-shrink-0" />
                      )}
                    </div>
                  );
                })
              )}
            </div>
          </div>
        )}
      </div>
    );
  }
);

Select.displayName = 'Select';
