// packages/vue/src/components/ListItem.vue
<template>
  <div
    :role="clickable ? 'button' : undefined"
    :tabindex="clickable ? 0 : undefined"
    @click="handleClick"
    @keydown="handleKeyDown"
    :class="itemClasses"
  >
    <div v-if="$slots.leftIcon" class="flex-shrink-0 mr-3 flex items-center justify-center">
      <slot name="leftIcon" />
    </div>
    
    <div class="flex-1 flex flex-col gap-y-0.5 min-w-0">
      <span :class="titleClasses">
        {{ title }}
      </span>
      <span v-if="description" :class="descriptionClasses">
        {{ description }}
      </span>
    </div>
    
    <div v-if="$slots.rightIcon" class="flex-shrink-0 ml-3 flex items-center justify-center">
      <slot name="rightIcon" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

export interface ListItemProps {
  title: string;
  description?: string;
  clickable?: boolean;
  active?: boolean;
  class?: string;
}

const props = withDefaults(defineProps<ListItemProps>(), {
  clickable: false,
  active: false,
  class: '',
});

const emit = defineEmits<{
  'click': [];
}>();

const handleKeyDown = (e: KeyboardEvent) => {
  if (props.clickable && (e.key === 'Enter' || e.key === ' ')) {
    e.preventDefault();
    emit('click');
  }
};

const handleClick = () => {
  if (props.clickable) {
    emit('click');
  }
};

const itemClasses = computed(() => {
  return [
    'w-full flex items-center',
    'px-4 py-3',
    'rounded-lg',
    'transition-all duration-200',
    props.active
      ? 'bg-primary text-primary-foreground'
      : 'bg-[hsl(var(--card))]',
    props.clickable && [
      'cursor-pointer',
      props.active 
        ? 'hover:bg-primary/90'
        : 'hover:bg-muted active:bg-muted/80',
      'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--ring))] focus-visible:ring-offset-2'
    ],
    !props.clickable && 'cursor-default',
    props.class,
  ].flat().filter(Boolean).join(' ');
});

const titleClasses = computed(() => {
  return [
    'text-sm font-medium',
    props.active ? 'text-primary-foreground' : 'text-[hsl(var(--foreground))]',
  ].join(' ');
});

const descriptionClasses = computed(() => {
  return [
    'text-sm',
    props.active ? 'text-primary-foreground/80' : 'text-[hsl(var(--muted-foreground))]',
  ].join(' ');
});
</script>

// packages/react/src/components/molecules/ListItem/ListItem.tsx
import React from 'react';
import { ListItemProps } from './types';
import { cn } from '../../../lib/utils';

export const ListItem: React.FC<ListItemProps> = ({
  title,
  description,
  leftIcon,
  rightIcon,
  clickable = false,
  active = false,
  onClick,
  className
}) => {
  const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>) => {
    if (clickable && onClick && (e.key === 'Enter' || e.key === ' ')) {
      e.preventDefault();
      onClick();
    }
  };

  const handleClick = () => {
    if (clickable && onClick) {
      onClick();
    }
  };

  return (
    <div
      role={clickable ? "button" : undefined}
      tabIndex={clickable ? 0 : undefined}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      className={cn(
        'w-full flex items-center',
        'px-4 py-3',
        'rounded-lg',
        'transition-all duration-200',
        active
          ? 'bg-primary text-primary-foreground'
          : 'bg-[hsl(var(--card))]',
        clickable && [
          'cursor-pointer',
          active 
            ? 'hover:bg-primary/90'
            : 'hover:bg-muted active:bg-muted/80',
          'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--ring))] focus-visible:ring-offset-2'
        ],
        !clickable && 'cursor-default',
        className
      )}
    >
      {leftIcon && (
        <div className="flex-shrink-0 mr-3 flex items-center justify-center">
          {leftIcon}
        </div>
      )}
      
      <div className="flex-1 flex flex-col gap-y-0.5 min-w-0">
        <span className={cn(
          "text-sm font-medium",
          active ? "text-primary-foreground" : "text-[hsl(var(--foreground))]"
        )}>
          {title}
        </span>
        {description && (
          <span className={cn(
            "text-sm",
            active ? "text-primary-foreground/80" : "text-[hsl(var(--muted-foreground))]"
          )}>
            {description}
          </span>
        )}
      </div>
      
      {rightIcon && (
        <div className="flex-shrink-0 ml-3 flex items-center justify-center">
          {rightIcon}
        </div>
      )}
    </div>
  );
};
