// packages/vue/src/components/Divider.vue
<template>
  <div
    :class="dividerClasses"
    role="separator"
  />
</template>

<script setup lang="ts">
import { computed } from 'vue';

export interface DividerProps {
  orientation?: 'horizontal' | 'vertical';
  class?: string;
}

const props = withDefaults(defineProps<DividerProps>(), {
  orientation: 'horizontal',
  class: '',
});

const dividerClasses = computed(() => {
  const orientationClasses = props.orientation === 'horizontal' 
    ? 'w-full h-px' 
    : 'h-full w-px';
  
  return [
    'bg-border',
    orientationClasses,
    props.class,
  ].filter(Boolean).join(' ');
});
</script>

// packages/angular/src/lib/components/atoms/divider/divider.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

export type DividerOrientation = 'horizontal' | 'vertical';

@Component({
  selector: 'ds-divider',
  standalone: true,
  imports: [CommonModule],
  styles: [`
    :host {
      display: block;
    }
  `],
  template: `
    <div
      [class]="dividerClasses"
      role="separator"
    ></div>
  `
})
export class DividerComponent {
  @Input() orientation: DividerOrientation = 'horizontal';

  get dividerClasses(): string {
    const classes = ['bg-border'];
    
    if (this.orientation === 'horizontal') {
      classes.push('w-full', 'h-px');
    } else {
      classes.push('h-full', 'w-px');
    }
    
    return classes.join(' ');
  }
}
