// packages/react/src/components/molecules/Breadcrumbs/Breadcrumbs.tsx
import React from 'react';
import { BreadcrumbsProps } from './types';
import { cn } from '../../../lib/utils';
import { ChevronRight } from 'lucide-react';
import { Icon } from '../../atoms/Icon';

export const Breadcrumbs: React.FC<BreadcrumbsProps> = ({ 
  items, 
  separator,
  className 
}) => {
  const defaultSeparator = (
    <Icon size={16}>
      <ChevronRight className="w-full h-full" />
    </Icon>
  );

  const separatorElement = separator !== undefined ? separator : defaultSeparator;

  return (
    <nav 
      className={cn(
        'flex items-center gap-x-1.5 text-sm',
        className
      )}
      role="navigation"
      aria-label="Breadcrumb"
    >
      {items.map((item, index) => {
        const isLast = index === items.length - 1;
        const hasHref = Boolean(item.href);
        
        return (
          <React.Fragment key={index}>
            {isLast ? (
              <span className="font-medium text-[hsl(var(--foreground))]">
                {item.label}
              </span>
            ) : hasHref ? (
              <a
                href={item.href}
                className="inline-flex items-center text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--primary))] transition-colors duration-200"
              >
                {item.label}
              </a>
            ) : (
              <span className="inline-flex items-center text-[hsl(var(--muted-foreground))]">
                {item.label}
              </span>
            )}
            
            {!isLast && (
              <span className="flex-shrink-0 text-[hsl(var(--muted-foreground))]">
                {separatorElement}
              </span>
            )}
          </React.Fragment>
        );
      })}
    </nav>
  );
};

// packages/vue/src/components/Breadcrumbs.vue
<template>
  <nav 
    :class="['flex items-center gap-x-1.5 text-sm', props.class]"
    role="navigation"
    aria-label="Breadcrumb"
  >
    <template v-for="(item, index) in items" :key="index">
      <span v-if="isLast(index)" class="font-medium text-[hsl(var(--foreground))]">
        {{ item.label }}
      </span>
      <a
        v-else-if="item.href"
        :href="item.href"
        class="inline-flex items-center text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--primary))] transition-colors duration-200"
      >
        {{ item.label }}
      </a>
      <span v-else class="inline-flex items-center text-[hsl(var(--muted-foreground))]">
        {{ item.label }}
      </span>
      
      <span
        v-if="!isLast(index)"
        class="flex-shrink-0 text-[hsl(var(--muted-foreground))]"
      >
        <slot name="separator">
          <svg
            class="w-4 h-4"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <polyline points="9 18 15 12 9 6"></polyline>
          </svg>
        </slot>
      </span>
    </template>
  </nav>
</template>

<script setup lang="ts">
export interface BreadcrumbItem {
  label: string;
  href?: string;
}

export interface BreadcrumbsProps {
  items: BreadcrumbItem[];
  class?: string;
}

const props = withDefaults(defineProps<BreadcrumbsProps>(), {
  class: '',
});

const isLast = (index: number) => index === props.items.length - 1;
</script>
