// packages/angular/src/lib/components/organisms/kpi-card/kpi-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

export type KpiTrend = 'up' | 'down' | 'neutral';

@Component({
  selector: 'ds-kpi-card',
  standalone: true,
  imports: [CommonModule],
  styles: [`
    :host {
      display: block;
    }
  `],
  template: `
    <div
      role="group"
      [attr.aria-label]="'KPI ' + label"
      class="rounded-md bg-card border border-border shadow-sm px-5 py-4 flex flex-col gap-1 transition-colors duration-200 hover:shadow-md"
    >
      <!-- Header: Icon and Label -->
      <div class="flex items-center justify-between mb-1">
        <span class="text-sm font-medium text-muted-foreground">
          {{ label }}
        </span>
        <div *ngIf="hasIcon" class="text-foreground">
          <ng-content select="[slot=icon]"></ng-content>
        </div>
      </div>

      <!-- Value -->
      <div class="text-2xl font-semibold text-foreground">
        {{ value }}
      </div>

      <!-- Trend -->
      <div *ngIf="trendValue" [class]="trendClasses">
        <svg
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        >
          <ng-container [ngSwitch]="trend">
            <path *ngSwitchCase="'up'" d="m18 15-6-6-6 6"/>
            <path *ngSwitchCase="'down'" d="m6 9 6 6 6-6"/>
            <path *ngSwitchCase="'neutral'" d="M5 12h14"/>
          </ng-container>
        </svg>
        <span>{{ trendValue }}</span>
      </div>
    </div>
  `
})
export class KpiCardComponent {
  @Input() label: string = '';
  @Input() value: string = '';
  @Input() trend: KpiTrend = 'neutral';
  @Input() trendValue?: string;
  @Input() hasIcon: boolean = false;

  get trendClasses(): string {
    const classes = [
      'flex',
      'items-center',
      'gap-1',
      'text-sm',
      'font-medium'
    ];
    
    switch (this.trend) {
      case 'up':
        classes.push('text-green-600', 'dark:text-green-400');
        break;
      case 'down':
        classes.push('text-red-600', 'dark:text-red-400');
        break;
      case 'neutral':
        classes.push('text-muted-foreground');
        break;
    }
    
    return classes.join(' ');
  }
}

// packages/vue/src/components/KpiCard.vue
<template>
  <div
    role="group"
    :aria-label="`KPI ${label}`"
    :class="cardClasses"
  >
    <!-- Header: Icon and Label -->
    <div class="flex items-center justify-between mb-1">
      <span class="text-sm font-medium text-[hsl(var(--muted-foreground))]">
        {{ label }}
      </span>
      <div v-if="$slots.icon" class="text-[hsl(var(--foreground))]">
        <slot name="icon" />
      </div>
    </div>

    <!-- Value -->
    <div class="text-2xl font-semibold text-[hsl(var(--foreground))]">
      {{ value }}
    </div>

    <!-- Trend -->
    <div
      v-if="trendValue"
      :class="trendClasses"
    >
      <svg
        class="w-4 h-4"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <template v-if="trend === 'up'">
          <line x1="12" y1="19" x2="12" y2="5"></line>
          <polyline points="5 12 12 5 19 12"></polyline>
        </template>
        <template v-else-if="trend === 'down'">
          <line x1="12" y1="5" x2="12" y2="19"></line>
          <polyline points="19 12 12 19 5 12"></polyline>
        </template>
        <template v-else>
          <line x1="5" y1="12" x2="19" y2="12"></line>
        </template>
      </svg>
      <span>{{ trendValue }}</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

export type KpiTrend = 'up' | 'down' | 'neutral';

export interface KpiCardProps {
  label: string;
  value: string | number;
  trend?: KpiTrend;
  trendValue?: string;
  class?: string;
}

const props = withDefaults(defineProps<KpiCardProps>(), {
  trend: 'neutral',
  class: '',
});

const cardClasses = computed(() => {
  return [
    'rounded-md',
    'bg-[hsl(var(--card))]',
    'border border-[hsl(var(--border))]',
    'shadow-sm',
    'px-5 py-4',
    'flex flex-col gap-1',
    'transition-colors duration-200',
    'hover:shadow-md',
    props.class,
  ].filter(Boolean).join(' ');
});

const getTrendColorClass = (): string => {
  const colorMap: Record<KpiTrend, string> = {
    up: 'text-[hsl(var(--success))]',
    down: 'text-[hsl(var(--destructive))]',
    neutral: 'text-[hsl(var(--muted-foreground))]',
  };
  return colorMap[props.trend];
};

const trendClasses = computed(() => {
  return [
    'flex items-center gap-1',
    'text-sm font-medium',
    getTrendColorClass(),
  ].join(' ');
});
</script>
