// packages/angular/src/lib/components/molecules/list-item/list-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'ds-list-item',
  standalone: true,
  imports: [CommonModule],
  styles: [`
    :host {
      display: block;
    }
  `],
  template: `
    <div
      [attr.role]="clickable ? 'button' : null"
      [attr.tabindex]="clickable ? 0 : null"
      (click)="handleClick()"
      (keydown)="handleKeyDown($event)"
      [class]="listItemClasses"
    >
      <div *ngIf="hasLeftIcon" class="flex-shrink-0 mr-3 flex items-center justify-center">
        <ng-content select="[slot=leftIcon]"></ng-content>
      </div>
      
      <div class="flex-1 flex flex-col gap-y-0.5 min-w-0">
        <span [class]="titleClasses">
          {{ title }}
        </span>
        <span *ngIf="description" [class]="descriptionClasses">
          {{ description }}
        </span>
      </div>
      
      <div *ngIf="hasRightIcon" class="flex-shrink-0 ml-3 flex items-center justify-center">
        <ng-content select="[slot=rightIcon]"></ng-content>
      </div>
    </div>
  `
})
export class ListItemComponent {
  @Input() title: string = '';
  @Input() description?: string;
  @Input() clickable: boolean = false;
  @Input() active: boolean = false;
  @Input() hasLeftIcon: boolean = false;
  @Input() hasRightIcon: boolean = false;
  
  @Output() itemClick = new EventEmitter<void>();
  @Output() onClick = new EventEmitter<void>();

  get listItemClasses(): string {
    const classes = [
      'w-full',
      'flex',
      'items-center',
      'px-4',
      'py-3',
      'rounded-lg',
      'transition-all',
      'duration-200'
    ];
    
    if (this.active) {
      classes.push('bg-primary', 'text-primary-foreground');
    } else {
      classes.push('bg-card');
    }
    
    if (this.clickable) {
      classes.push('cursor-pointer');
      if (this.active) {
        classes.push('hover:bg-primary/90');
      } else {
        classes.push('hover:bg-muted', 'active:bg-muted/80');
      }
      classes.push('focus-visible:outline-none', 'focus-visible:ring-2', 'focus-visible:ring-ring', 'focus-visible:ring-offset-2');
    } else {
      classes.push('cursor-default');
    }
    
    return classes.join(' ');
  }

  get titleClasses(): string {
    const classes = ['text-sm', 'font-medium'];
    if (this.active) {
      classes.push('text-primary-foreground');
    } else {
      classes.push('text-foreground');
    }
    return classes.join(' ');
  }

  get descriptionClasses(): string {
    const classes = ['text-sm'];
    if (this.active) {
      classes.push('text-primary-foreground/80');
    } else {
      classes.push('text-muted-foreground');
    }
    return classes.join(' ');
  }

  handleClick(): void {
    if (this.clickable) {
      this.itemClick.emit();
      this.onClick.emit();
    }
  }

  handleKeyDown(event: KeyboardEvent): void {
    if (this.clickable && (event.key === 'Enter' || event.key === ' ')) {
      event.preventDefault();
      this.itemClick.emit();
      this.onClick.emit();
    }
  }
}

// packages/vue/src/components/ListItem.vue
<template>
  <div
    :role="clickable ? 'button' : undefined"
    :tabindex="clickable ? 0 : undefined"
    @click="handleClick"
    @keydown="handleKeyDown"
    :class="itemClasses"
  >
    <div v-if="$slots.leftIcon" class="flex-shrink-0 mr-3 flex items-center justify-center">
      <slot name="leftIcon" />
    </div>
    
    <div class="flex-1 flex flex-col gap-y-0.5 min-w-0">
      <span :class="titleClasses">
        {{ title }}
      </span>
      <span v-if="description" :class="descriptionClasses">
        {{ description }}
      </span>
    </div>
    
    <div v-if="$slots.rightIcon" class="flex-shrink-0 ml-3 flex items-center justify-center">
      <slot name="rightIcon" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

export interface ListItemProps {
  title: string;
  description?: string;
  clickable?: boolean;
  active?: boolean;
  class?: string;
}

const props = withDefaults(defineProps<ListItemProps>(), {
  clickable: false,
  active: false,
  class: '',
});

const emit = defineEmits<{
  'click': [];
}>();

const handleKeyDown = (e: KeyboardEvent) => {
  if (props.clickable && (e.key === 'Enter' || e.key === ' ')) {
    e.preventDefault();
    emit('click');
  }
};

const handleClick = () => {
  if (props.clickable) {
    emit('click');
  }
};

const itemClasses = computed(() => {
  return [
    'w-full flex items-center',
    'px-4 py-3',
    'rounded-lg',
    'transition-all duration-200',
    props.active
      ? 'bg-primary text-primary-foreground'
      : 'bg-[hsl(var(--card))]',
    props.clickable && [
      'cursor-pointer',
      props.active 
        ? 'hover:bg-primary/90'
        : 'hover:bg-muted active:bg-muted/80',
      'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--ring))] focus-visible:ring-offset-2'
    ],
    !props.clickable && 'cursor-default',
    props.class,
  ].flat().filter(Boolean).join(' ');
});

const titleClasses = computed(() => {
  return [
    'text-sm font-medium',
    props.active ? 'text-primary-foreground' : 'text-[hsl(var(--foreground))]',
  ].join(' ');
});

const descriptionClasses = computed(() => {
  return [
    'text-sm',
    props.active ? 'text-primary-foreground/80' : 'text-[hsl(var(--muted-foreground))]',
  ].join(' ');
});
</script>
