// packages/angular/src/lib/components/atoms/skeleton/skeleton.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

export type SkeletonVariant = 'rectangular' | 'circular' | 'text';

@Component({
  selector: 'ds-skeleton',
  standalone: true,
  imports: [CommonModule],
  styles: [`
    :host {
      display: block;
    }
  `],
  template: `
    <div
      [class]="skeletonClasses"
      [style.width]="width"
      [style.height]="height"
    ></div>
  `
})
export class SkeletonComponent {
  @Input() width?: string | number;
  @Input() height?: string | number;
  @Input() variant: SkeletonVariant = 'rectangular';

  get skeletonClasses(): string {
    const classes = [
      'animate-pulse',
      'bg-muted'
    ];
    
    // Variant classes
    switch (this.variant) {
      case 'rectangular':
        classes.push('rounded-md');
        break;
      case 'circular':
        classes.push('rounded-full');
        break;
      case 'text':
        classes.push('rounded');
        break;
    }
    
    return classes.join(' ');
  }
}

// packages/vue/src/components/Skeleton.vue
<template>
  <div
    :class="skeletonClasses"
    :style="skeletonStyles"
  />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { SkeletonVariant } from './types';

export interface SkeletonProps {
  width?: string;
  height?: string;
  variant?: SkeletonVariant;
  class?: string;
}

const props = withDefaults(defineProps<SkeletonProps>(), {
  variant: 'rectangular',
  class: '',
});

const variantClasses: Record<SkeletonVariant, string> = {
  rectangular: 'rounded-md',
  circular: 'rounded-full',
  text: 'rounded',
};

const skeletonClasses = computed(() => {
  return [
    'animate-pulse bg-muted',
    variantClasses[props.variant],
    props.class,
  ].filter(Boolean).join(' ');
});

const skeletonStyles = computed(() => ({
  width: props.width,
  height: props.height,
}));
</script>
