// packages/react/src/components/organisms/UserMenu/UserMenu.tsx
import React, { useState, useRef, useEffect } from 'react';
import { UserMenuProps } from './types';
import { cn } from '../../../lib/utils';
import { ChevronDown } from 'lucide-react';
import { Icon } from '../../atoms/Icon';
import { Avatar } from '../../atoms/Avatar';

export const UserMenu: React.FC<UserMenuProps> = ({
  user,
  items,
  onSelect,
  className
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  // Handle click outside to close
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };

    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [isOpen]);

  // Handle escape key to close
  useEffect(() => {
    const handleEscape = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && isOpen) {
        setIsOpen(false);
      }
    };

    if (isOpen) {
      document.addEventListener('keydown', handleEscape);
    }

    return () => {
      document.removeEventListener('keydown', handleEscape);
    };
  }, [isOpen]);

  const handleToggle = () => {
    setIsOpen(!isOpen);
  };

  const handleItemClick = (value: string) => {
    onSelect(value);
    setIsOpen(false);
  };

  const handleKeyDown = (event: React.KeyboardEvent) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      handleToggle();
    }
  };

  return (
    <div ref={menuRef} className={cn('relative', className)}>
      {/* Trigger Button */}
      <button
        type="button"
        onClick={handleToggle}
        onKeyDown={handleKeyDown}
        role="button"
        aria-expanded={isOpen}
        aria-haspopup="menu"
        className={cn(
          'flex items-center gap-3',
          'px-3 py-2',
          'rounded-md',
          'hover:bg-[hsl(var(--muted))]',
          'cursor-pointer',
          'transition-colors duration-200',
          'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--ring))]'
        )}
      >
        {/* Avatar */}
        <Avatar
          src={user.avatarSrc}
          fallback={user.name.substring(0, 2).toUpperCase()}
          alt={user.name}
          size="md"
        />

        {/* User Info */}
        <div className="flex flex-col leading-tight text-left">
          <span className="text-sm font-medium text-[hsl(var(--foreground))]">
            {user.name}
          </span>
          {user.email && (
            <span className="text-xs text-[hsl(var(--muted-foreground))]">
              {user.email}
            </span>
          )}
        </div>

        {/* Chevron */}
        <Icon size={16}>
          <ChevronDown
            className={cn(
              'w-full h-full text-[hsl(var(--muted-foreground))]',
              'transition-transform duration-200',
              isOpen && 'rotate-180'
            )}
          />
        </Icon>
      </button>

      {/* Dropdown Menu */}
      {isOpen && (
        <div
          role="menu"
          className={cn(
            'absolute mt-2 right-0',
            'bg-[hsl(var(--card))]',
            'border border-[hsl(var(--border))]',
            'shadow-lg',
            'rounded-md',
            'py-2',
            'min-w-[180px]',
            'z-50',
            'flex flex-col'
          )}
        >
          {items.map((item) => (
            <button
              key={item.value}
              type="button"
              onClick={() => handleItemClick(item.value)}
              role="menuitem"
              className={cn(
                'px-4 py-2.5',
                'flex items-center gap-3',
                'text-sm text-[hsl(var(--foreground))]',
                'hover:bg-[hsl(var(--muted))]',
                'transition-colors duration-200',
                'cursor-pointer',
                'text-left',
                'w-full'
              )}
            >
              {item.icon && (
                <div className="text-[hsl(var(--foreground))]">
                  {item.icon}
                </div>
              )}
              <span>{item.label}</span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
};

// packages/vue/src/components/UserMenu.vue
<template>
  <div ref="menuRef" :class="['relative', props.class]">
    <!-- Trigger Button -->
    <button
      type="button"
      @click="handleToggle"
      @keydown="handleKeyDown"
      role="button"
      :aria-expanded="isOpen"
      aria-haspopup="menu"
      :class="triggerClasses"
    >
      <!-- Avatar -->
      <div
        :class="avatarClasses"
        :style="{ backgroundImage: user.avatarSrc ? `url(${user.avatarSrc})` : undefined }"
      >
        <span v-if="!user.avatarSrc" class="text-sm font-medium">
          {{ getFallback }}
        </span>
      </div>

      <!-- User Info -->
      <div class="flex flex-col leading-tight text-left">
        <span class="text-sm font-medium text-[hsl(var(--foreground))]">
          {{ user.name }}
        </span>
        <span v-if="user.email" class="text-xs text-[hsl(var(--muted-foreground))]">
          {{ user.email }}
        </span>
      </div>

      <!-- Chevron -->
      <svg
        :class="chevronClasses"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      >
        <polyline points="6 9 12 15 18 9"></polyline>
      </svg>
    </button>

    <!-- Dropdown Menu -->
    <div
      v-if="isOpen"
      role="menu"
      :class="menuClasses"
    >
      <button
        v-for="item in items"
        :key="item.value"
        type="button"
        @click="handleItemClick(item.value)"
        role="menuitem"
        :class="menuItemClasses"
      >
        <div v-if="item.icon" class="text-[hsl(var(--foreground))]">
          {{ item.icon }}
        </div>
        <span>{{ item.label }}</span>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';

export interface UserMenuItem {
  label: string;
  value: string;
  icon?: string;
}

export interface User {
  name: string;
  email?: string;
  avatarSrc?: string;
}

export interface UserMenuProps {
  user: User;
  items: UserMenuItem[];
  class?: string;
}

const props = withDefaults(defineProps<UserMenuProps>(), {
  class: '',
});

const emit = defineEmits<{
  'select': [value: string];
}>();

const menuRef = ref<HTMLDivElement | null>(null);
const isOpen = ref(false);

const handleToggle = () => {
  isOpen.value = !isOpen.value;
};

const handleItemClick = (value: string) => {
  emit('select', value);
  isOpen.value = false;
};

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    handleToggle();
  }
};

const getFallback = computed(() => props.user.name.substring(0, 2).toUpperCase());

// Handle click outside
const handleClickOutside = (event: MouseEvent) => {
  if (menuRef.value && !menuRef.value.contains(event.target as Node)) {
    isOpen.value = false;
  }
};

// Handle escape key
const handleEscape = (event: KeyboardEvent) => {
  if (event.key === 'Escape' && isOpen.value) {
    isOpen.value = false;
  }
};

watch(isOpen, (newValue) => {
  if (newValue) {
    document.addEventListener('mousedown', handleClickOutside);
    document.addEventListener('keydown', handleEscape);
  } else {
    document.removeEventListener('mousedown', handleClickOutside);
    document.removeEventListener('keydown', handleEscape);
  }
});

const triggerClasses = [
  'flex items-center gap-3',
  'px-3 py-2',
  'rounded-md',
  'hover:bg-[hsl(var(--muted))]',
  'cursor-pointer',
  'transition-colors duration-200',
  'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--ring))]',
].join(' ');

const avatarClasses = [
  'w-10 h-10',
  'rounded-full',
  'bg-primary text-primary-foreground',
  'flex items-center justify-center',
  'bg-cover bg-center',
].join(' ');

const chevronClasses = computed(() => {
  return [
    'w-4 h-4 text-[hsl(var(--muted-foreground))]',
    'transition-transform duration-200',
    isOpen.value && 'rotate-180',
  ].filter(Boolean).join(' ');
});

const menuClasses = [
  'absolute mt-2 right-0',
  'bg-[hsl(var(--card))]',
  'border border-[hsl(var(--border))]',
  'shadow-lg',
  'rounded-md',
  'py-2',
  'min-w-[180px]',
  'z-50',
  'flex flex-col',
].join(' ');

const menuItemClasses = [
  'px-4 py-2.5',
  'flex items-center gap-3',
  'text-sm text-[hsl(var(--foreground))]',
  'hover:bg-[hsl(var(--muted))]',
  'transition-colors duration-200',
  'cursor-pointer',
  'text-left',
  'w-full',
].join(' ');
</script>
