// packages/vue/src/components/Button.vue
<template>
  <button
    :type="type"
    role="button"
    :aria-disabled="isDisabled"
    :aria-busy="loading"
    :class="buttonClasses"
    :disabled="isDisabled"
    v-bind="$attrs"
  >
    <!-- Loading spinner -->
    <span
      v-if="loading"
      :class="['animate-spin rounded-full border-2 border-current border-t-transparent', iconSizeClasses]"
      aria-hidden="true"
    />
    
    <!-- Left icon slot -->
    <span
      v-if="!loading && $slots.leftIcon"
      :class="['flex-shrink-0', iconSizeClasses]"
      aria-hidden="true"
    >
      <slot name="leftIcon" />
    </span>
    
    <!-- Main content -->
    <span v-if="$slots.default">
      <slot />
    </span>
    
    <!-- Right icon slot -->
    <span
      v-if="!loading && $slots.rightIcon"
      :class="['flex-shrink-0', iconSizeClasses]"
      aria-hidden="true"
    >
      <slot name="rightIcon" />
    </span>
  </button>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { cn } from '../lib/utils';
import type { ButtonProps } from './types';

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'primary',
  size: 'md',
  loading: false,
  fullWidth: false,
  disabled: false,
  type: 'button',
});

defineOptions({
  inheritAttrs: false,
});

const buttonVariants = {
  primary: 'bg-primary text-primary-foreground hover:bg-primary/90',
  secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
  ghost: 'hover:bg-accent hover:text-accent-foreground',
  outline: 'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
  destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
  link: 'text-primary underline-offset-4 hover:underline',
};

const buttonSizes = {
  sm: 'h-9 rounded-md px-3',
  md: 'h-10 px-4 py-2',
  lg: 'h-11 rounded-md px-8',
  icon: 'h-10 w-10',
};

const iconSizes = {
  sm: 'w-3.5 h-3.5',
  md: 'w-4 h-4',
  lg: 'w-5 h-5',
  icon: 'w-4 h-4',
};

const isDisabled = computed(() => props.disabled || props.loading);

const buttonClasses = computed(() => 
  cn(
    'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
    'disabled:pointer-events-none disabled:opacity-50',
    '[&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0',
    buttonVariants[props.variant],
    buttonSizes[props.size],
    props.fullWidth && 'w-full',
  )
);

const iconSizeClasses = computed(() => iconSizes[props.size]);
</script>

// packages/angular/src/lib/components/atoms/button/button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'outline' | 'destructive' | 'link';
export type ButtonSize = 'sm' | 'md' | 'lg' | 'icon';

@Component({
  selector: 'ui-button',
  standalone: true,
  imports: [CommonModule],
  styles: [`
    :host {
      display: inline-block;
    }
  `],
  template: `
    <button 
      [type]="type"
      [disabled]="disabled || loading"
      [class]="buttonClasses"
      (click)="onClick.emit($event)"
    >
      <!-- Loading spinner -->
      <svg 
        *ngIf="loading" 
        class="animate-spin -ml-1 mr-2 h-4 w-4" 
        xmlns="http://www.w3.org/2000/svg" 
        fill="none" 
        viewBox="0 0 24 24"
      >
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
      </svg>
      
      <!-- Left icon -->
      <ng-content select="[slot=leftIcon]"></ng-content>
      
      <!-- Content -->
      <ng-content></ng-content>
      
      <!-- Right icon -->
      <ng-content select="[slot=rightIcon]"></ng-content>
    </button>
  `
})
export class ButtonComponent {
  @Input() variant: ButtonVariant = 'primary';
  @Input() size: ButtonSize = 'md';
  @Input() loading = false;
  @Input() disabled = false;
  @Input() fullWidth = false;
  @Input() type: 'button' | 'submit' | 'reset' = 'button';
  @Input() class = '';
  
  // Output for click events
  @Output() onClick = new EventEmitter<MouseEvent>();

  get buttonClasses(): string {
    const baseClasses = [
      'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg text-sm font-medium',
      'ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50'
    ];

    const variantClasses: Record<ButtonVariant, string> = {
      primary: 'bg-primary text-primary-foreground hover:bg-primary/90',
      secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
      ghost: 'hover:bg-accent hover:text-accent-foreground',
      outline: 'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
      destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
      link: 'text-primary underline-offset-4 hover:underline',
    };

    const sizeClasses: Record<ButtonSize, string> = {
      sm: 'h-9 rounded-md px-3',
      md: 'h-10 px-4 py-2',
      lg: 'h-11 rounded-md px-8',
      icon: 'h-10 w-10'
    };

    const classes = [
      ...baseClasses,
      variantClasses[this.variant],
      sizeClasses[this.size],
      this.fullWidth ? 'w-full' : '',
      this.class
    ];

    return classes.filter(Boolean).join(' ');
  }
}
