// packages/vue/src/components/Modal.vue
<template>
  <Teleport to="body">
    <div
      v-if="open"
      class="fixed inset-0 bg-black/40 backdrop-blur-sm flex items-center justify-center z-50 p-4"
      @click="onClose"
      role="dialog"
      aria-modal="true"
      :aria-labelledby="title ? 'modal-title' : undefined"
    >
      <!-- Modal container -->
      <div
        @click.stop
        :class="modalClasses"
      >
        <!-- Header -->
        <div
          v-if="title || closeButton"
          class="px-6 py-4 border-b border-[hsl(var(--border))] flex items-center justify-between flex-shrink-0"
        >
          <h2
            v-if="title"
            id="modal-title"
            class="text-lg font-semibold text-[hsl(var(--foreground))]"
          >
            {{ title }}
          </h2>
          <button
            v-if="closeButton"
            type="button"
            @click="onClose"
            aria-label="Close modal"
            :class="[
              'p-2 rounded-md',
              'hover:bg-[hsl(var(--accent))]',
              'transition-colors duration-200',
              'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[hsl(var(--ring))]',
              !title && 'ml-auto'
            ]"
          >
            <svg
              class="w-5 h-5"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <line x1="18" y1="6" x2="6" y2="18"></line>
              <line x1="6" y1="6" x2="18" y2="18"></line>
            </svg>
          </button>
        </div>

        <!-- Body -->
        <div class="px-6 py-4 text-[hsl(var(--foreground))] flex-1 overflow-y-auto">
          <slot />
        </div>

        <!-- Footer -->
        <div
          v-if="$slots.footer"
          class="px-6 py-4 border-t border-[hsl(var(--border))] flex justify-end gap-2 flex-shrink-0"
        >
          <slot name="footer" />
        </div>
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { computed, watch } from 'vue';

export type ModalSize = 'sm' | 'md' | 'lg';

export interface ModalProps {
  open: boolean;
  title?: string;
  size?: ModalSize;
  closeButton?: boolean;
  class?: string;
}

const props = withDefaults(defineProps<ModalProps>(), {
  size: 'md',
  closeButton: true,
  class: '',
});

const emit = defineEmits<{
  'close': [];
}>();

const onClose = () => {
  emit('close');
};

// Handle escape key
watch(() => props.open, (newOpen) => {
  const handleEscape = (e: KeyboardEvent) => {
    if (e.key === 'Escape' && newOpen) {
      onClose();
    }
  };

  if (newOpen) {
    document.addEventListener('keydown', handleEscape);
    return () => document.removeEventListener('keydown', handleEscape);
  }
});

const sizeClasses: Record<ModalSize, string> = {
  sm: 'max-w-sm',
  md: 'max-w-lg',
  lg: 'max-w-2xl',
};

const modalClasses = computed(() => {
  return [
    'w-full',
    sizeClasses[props.size],
    'max-h-[90vh]',
    'bg-[hsl(var(--card))]',
    'rounded-lg',
    'shadow-xl',
    'border border-[hsl(var(--border))]',
    'overflow-y-auto',
    'flex flex-col',
    props.class,
  ].filter(Boolean).join(' ');
});
</script>

// packages/angular/src/lib/components/organisms/modal/modal.component.ts
import { Component, Input, Output, EventEmitter, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';

export type ModalSize = 'sm' | 'md' | 'lg';

@Component({
  selector: 'ds-modal',
  standalone: true,
  imports: [CommonModule],
  styles: [`
    :host {
      display: contents;
    }
  `],
  template: `
    <div
      *ngIf="open"
      class="fixed inset-0 bg-black/40 backdrop-blur-sm flex items-center justify-center z-50 p-4"
      (click)="handleOverlayClick()"
      role="dialog"
      attr.aria-modal="true"
      [attr.aria-labelledby]="title ? 'modal-title' : null"
    >
      <!-- Modal container -->
      <div
        (click)="$event.stopPropagation()"
        [class]="modalClasses"
      >
        <!-- Header -->
        <div
          *ngIf="title || closeButton"
          class="px-6 py-4 border-b border-border flex items-center justify-between flex-shrink-0"
        >
          <h2
            *ngIf="title"
            id="modal-title"
            class="text-lg font-semibold text-foreground"
          >
            {{ title }}
          </h2>
          <button
            *ngIf="closeButton"
            type="button"
            (click)="onClose.emit()"
            aria-label="Close modal"
            [class]="closeButtonClasses"
          >
            <svg
              width="20"
              height="20"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path d="M18 6 6 18"/>
              <path d="m6 6 12 12"/>
            </svg>
          </button>
        </div>

        <!-- Body -->
        <div class="px-6 py-4 text-foreground flex-1 overflow-y-auto">
          <ng-content></ng-content>
        </div>

        <!-- Footer -->
        <div
          *ngIf="hasFooter"
          class="px-6 py-4 border-t border-border flex justify-end gap-2 flex-shrink-0"
        >
          <ng-content select="[slot=footer]"></ng-content>
        </div>
      </div>
    </div>
  `
})
export class ModalComponent {
  @Input() open: boolean = false;
  @Input() title?: string;
  @Input() size: ModalSize = 'md';
  @Input() closeButton: boolean = true;
  @Input() hasFooter: boolean = false;
  
  @Output() onClose = new EventEmitter<void>();

  @HostListener('document:keydown.escape')
  onEscape() {
    if (this.open) {
      this.onClose.emit();
    }
  }

  get modalClasses(): string {
    const classes = [
      'w-full',
      'max-h-[90vh]',
      'bg-card',
      'rounded-lg',
      'shadow-xl',
      'border',
      'border-border',
      'overflow-y-auto',
      'flex',
      'flex-col'
    ];
    
    // Size classes
    switch (this.size) {
      case 'sm':
        classes.push('max-w-sm');
        break;
      case 'md':
        classes.push('max-w-lg');
        break;
      case 'lg':
        classes.push('max-w-2xl');
        break;
    }
    
    return classes.join(' ');
  }

  get closeButtonClasses(): string {
    const classes = [
      'p-2',
      'rounded-md',
      'hover:bg-accent',
      'transition-colors',
      'duration-200',
      'focus-visible:outline-none',
      'focus-visible:ring-2',
      'focus-visible:ring-ring'
    ];
    
    if (!this.title) {
      classes.push('ml-auto');
    }
    
    return classes.join(' ');
  }

  handleOverlayClick(): void {
    this.onClose.emit();
  }
}
