// packages/vue/src/components/KBD.vue
<template>
  <kbd
    :class="kbdClasses"
  >
    <slot />
  </kbd>
</template>

<script setup lang="ts">
import { computed } from 'vue';

export interface KBDProps {
  class?: string;
}

const props = withDefaults(defineProps<KBDProps>(), {
  class: '',
});

const kbdClasses = computed(() => {
  return [
    'inline-flex items-center justify-center px-2 py-1 text-xs font-semibold',
    'text-foreground bg-muted border border-border rounded shadow-sm',
    props.class,
  ].filter(Boolean).join(' ');
});
</script>

// packages/angular/src/lib/components/atoms/kbd/kbd.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'ds-kbd',
  standalone: true,
  imports: [CommonModule],
  styles: [`
    :host {
      display: inline-block;
    }
  `],
  template: `
    <kbd class="inline-flex items-center justify-center px-2 py-1 text-xs font-semibold text-foreground bg-muted border border-border rounded shadow-sm">
      <ng-content></ng-content>
    </kbd>
  `
})
export class KBDComponent {}
